image: ubuntu:16.04

stages:
  - test

services:
  - postgres:9.6

variables:
  POSTGRES_DB: dbname # set database
  POSTGRES_USER: username # set username
  POSTGRES_PASSWORD: ""  

before_script:
  - apt-get update
  - apt-get install -y jq
  - apt-get -y upgrade
  - apt-get -y install golang-1.9-go
  - echo "export PATH=\$PATH:/usr/lib/go-1.9/bin" >> ~/.profile
  - source ~/.profile
  - apt-get -y install postgresql postgresql-contrib

test:
  stage: test
  script:
    - psql --version
    - psql -h postgres -d dbname -U username -c "SELECT version();"
    - cd pghrep && make test
