image: ubuntu:16.04

stages:
  - test

variables:
  POSTGRES_DB: dbname # set database
  POSTGRES_USER: username # set username
  POSTGRES_PASSWORD: ""  

before_script:
  - apt-get update
  - apt-get install -y jq curl
  - apt-get -y upgrade
  - apt-get -y install golang-1.9-go
  - echo "export PATH=\$PATH:/usr/lib/go-1.9/bin" >> ~/.profile
  - source ~/.profile
  - apt-get -y install postgresql-11 postgresql-contrib-11 postgresql-client-11
  - psql --version

.test-check:
  script:
    - psql -h postgres -d dbname -U username -c "SELECT version();"
    - psql -h postgres -d dbname -U username -f .ci/h002.sql
    - ./checkup -h postgres --username username --project test --dbname dbname -e 1
    - data_dir=$(cat ./artifacts/test/nodes.json | jq -r '.last_check | .dir') && result=$(cat ./artifacts/test/json_reports/$data_dir/H002_non_indexed_fks.json | jq '.results .postgres .data') && ([[ "$result" == "[]" ]] || [[ "$result" == "null" ]]) && exit 101
    - psql -h postgres -d dbname -U username -f .ci/h002_step2.sql
    - rm -Rf ./artifacts/
    - ./checkup -h postgres --username username --project test --dbname dbname -e 1
    - data_dir=$(cat ./artifacts/test/nodes.json | jq -r '.last_check | .dir') && result=$(cat ./artifacts/test/json_reports/$data_dir/H002_non_indexed_fks.json | jq '.results .postgres .data') && echo "$result" && cat ./artifacts/test/json_reports/$data_dir/H002_non_indexed_fks.json && (! [[ "$result" == "[]" ]]) && exit 102
    - echo "Passed"
  
  
test-acceptance:
  stage: test
  before_script:
    - apt-get install -y postgresql-server-dev-11 && apt-get install -y postgresql-11-pg-stat-kcache
    - echo "local   all all trust" > /etc/postgresql/11/main/pg_hba.conf
    - echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/11/main/pg_hba.conf
    - echo "listen_addresses='*'" >> /etc/postgresql/11/main/postgresql.conf
    - echo "log_filename='postgresql-11-main.log'" >> /etc/postgresql/11/main/postgresql.conf
    - echo "shared_preload_libraries = 'pg_stat_statements,auto_explain,pg_stat_kcache'" >> /etc/postgresql/11/main/postgresql.conf
    - /etc/init.d/postgresql start && psql -U postgres -c 'create database $POSTGRES_DB;' && /etc/init.d/postgresql stop
    - psql -U postgres $POSTGRES_DB -b -c 'create extension if not exists pg_stat_statements;'
    - psql -U postgres $POSTGRES_DB -b -c 'create extension if not exists pg_stat_kcache;'
    - psql -U postgres $POSTGRES_DB -c "create role $POSTGRES_USER superuser login;
    - echo "#!/bin/bash" > /pg_start.sh && chmod a+x /pg_start.sh
    - printf "sudo -u postgres /usr/lib/postgresql/11/bin/postgres -D /var/lib/postgresql/11/main -c config_file=/etc/postgresql/11/main/postgresql.conf & \n" >> /pg_start.sh
    - echo "etcd" >> /pg_start.sh
    - /pg_start.sh
  script:
    - psql -h localhost -d dbname -U username -c "SELECT version();"
    - psql -h localhost -d dbname -U username -f .ci/test_db_dump.sql
    - ./checkup -h localhost --username username --project test --dbname dbname -e 1 > std.log 2> err.log
    - cp std.log ./artifacts/test/
    - cp err.log ./artifacts/test/
    - tar -cvf test_artifacts.tar ./artifacts/test/*
  artifacts:
    paths:
      - ./artifacts/test
      - ./std.log
      - ./err.log
    expire_in: 1 week

test-pghrep:
  stage: test
  script:
    - cd pghrep && make test

test-check-9.6:
  extends: ".test-check"
  stage: "test"
  services:
    - postgres:9.6

test-check-10:
  extends: ".test-check"
  stage: "test"
  services:
    - postgres:10

test-check-11:
  extends: ".test-check"
  stage: "test"
  services:
    - postgres:11

test-check-cli:
  services:
    - postgres:11
  stage: "test"
  script: |
    errcount=0
    printTail="                                                                      "
    for f in tests/cli_*.sh; do
      printf "$f${printTail:0:-${#f}}"
      bash "$f" -H
      status=$?
      if [ "$status" -ne 0 ]; then
        errcount="$(($errcount+1))"
      fi
    done
    if [ "$errcount" -ne 0 ]; then
      >&2 echo "Oh no! $errcount tests failed"
      exit 1
    fi
